### ISSUE TITLE
quoted fields and whitespace after a delimiter

### ISSUE THREAD

**Issue by mczhuzhu** [brutella/swift-csv#3]
The parser will accept a quoted field if the doublequote is placed immediately after the delimiter, like this:
a,b,c,"a quoted field, with an embedded delimiter"

but if the quoted field has whitespace between the previous delimiter and the first quote, the parser appears to believe it's in the middle of the field when it encounters the doublequote and doesn't treat the current field as quoted, hence the following  input:
a,b,c,   "a quoted field, with an embedded delimiter"

... is parsed into 5 fields: 'a', 'b',  'c',   '   "a quoted field',  ' with an embedded delimiter"' 
and it outputs a "Doublequote unexpected in unquoted field" message

**Comment by brutella** [comment]
I think that's correct behaviour.

> 2.4 [...] Spaces are considered part of a field and should not be ignored.
> [RFC 4180](https://tools.ietf.org/html/rfc4180#page-2)
